---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/your_cpanel_username/your_app_directory
    - cd $DEPLOY_PATH
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /opt/cpanel/ea-nodejs18/bin/npm run start
